version: "3.8"

services:
  mc:
    image: platform-image-dev:latest
    environment:
      - EULA=true
      - CONFIG_PATH="example-url-here"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: no
volumes:
  data: {}
