version: "3.8"

services:
  mc:
    image: platform-image-dev:latest
    env_file:
      - .env.docker-compose
    environment:
      - EULA=true
    ports:
      - "25565:25565"
    volumes:
      - type: tmpfs
        target: /data
        tmpfs:
          # 12 GB of tmp storage.
          size: "12884901888"
    stdin_open: true
    tty: true
    restart: "no"
